# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Kkrt < Formula
  desc "kkrt is CLI to operate EVM block proving"
  homepage "https://github.com/kkrt-labs/test-ci"
  version "0.3.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kkrt-labs/test-ci/releases/download/v0.3.4/test-ci_0.3.4_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c32439033a306dbb3c34231353ef63d968af204660d64fc71693fa3aac8c024d"

      def install
        bin.install "kkrtctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kkrt-labs/test-ci/releases/download/v0.3.4/test-ci_0.3.4_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c34537ada270867c55ab4ccc80b20aa1306e69e997d10ac53e3dc693daf78686"

      def install
        bin.install "kkrtctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kkrt-labs/test-ci/releases/download/v0.3.4/test-ci_0.3.4_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "4343c40b308141fb798c224e851227eda724c96d97a75e9b5867dced0d1e038a"

        def install
          bin.install "kkrtctl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kkrt-labs/test-ci/releases/download/v0.3.4/test-ci_0.3.4_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "f62df1f33d7eea8aa55ad6356aec26ecb91b4c2afda22cc92c8c70eecab68d16"

        def install
          bin.install "kkrtctl"
        end
      end
    end
  end
end
